name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
      - "library.properties"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "examples/**"
      - "src/**"
      - "library.properties"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:avr:uno
            platforms: |
              - name: arduino:avr
          - fqbn: esp32:esp32:esp32
            platforms: |
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
           - fqbn: esp8266:esp8266:huzzah
             platforms: |
               - name: esp8266:esp8266
                 source-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ESP32 platform dependencies
        if: startsWith(matrix.board.fqbn, 'esp32:esp32')
        run: pip3 install pyserial

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
          libraries: |
            - name: Adafruit GFX Library
            - name: PxMatrix LED MATRIX library
            - name: Time
            - name: NtpClientLib
            - source-path: ./src

      - name: Save memory usage change report as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SKETCHES_REPORTS_PATH }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
